"""Create tasks table

Revision ID: 835ada178678
Revises: 
Create Date: 2023-07-27 18:49:02.078792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '835ada178678'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
