# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build-and-test:
    docker:
      - image: cimg/node:20.6.0
    steps:
      - checkout
      - run:
          name: Change directory
          command: cd ./client
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  test:
    jobs:
      - build-and-test
