# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  node: circleci/node@5.0.2

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build-and-test:
    docker:
      - image: cimg/node:20.6.0
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ~/eventexperienceapp/client
          pkg-manager: npm
      - run:
          name: Run tests
          command: cd client && npm test

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  test:
    jobs:
      - build-and-test
